apiVersion: v2
description: "Unified MMLI Backend for AlphaSynthesis"
name: mmli-backend
version: 1.0.0
dependencies:
- name: postgresql
  version: ~12.2.2
  repository: "https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami"
  condition: postgresql.enabled
- name: minio
  version: ~12.6.4
  repository: "https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami"
  condition: minio.enabled
