---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mmli-shared-job-data
  # namespace: alphasynthesis    # mmli1/mmli2 prod
  # namespace: staging           # mmli1/mmli2 staging
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
#  storageClassName: nfs-taiga
#  volumeName: pvc-60b03632-3186-41b1-8dd3-ece79936cac7


